- name: Download the file
  copy:
    src: /home/tldart/Documents/Projects/terraform-academy/resources/html_demo_site-main.zip
    dest: /tmp/



- name: Extract file
  unarchive:
    src:  /tmp/html_demo_site-main.zip
    dest: /var/www/html
    remote_src: true
    mode: '0755'
    owner: 'www-data'
    group: 'www-data'
    
