- name: Update Ubuntu distro
  apt:
    upgrade: "yes"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  become: true
  tags:
    - skip_ansible_lint

- name: Update apt cache and install unzip
  become: true
  apt:
    name: unzip
    update_cache: yes
    state: present